apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: elasticsearch-exporter
  namespace: monitoring
  labels:
    app: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: staging
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: elasticsearch-exporter
        image: justwatch/elasticsearch_exporter:1.0.2
      - command:
        - /bin/elasticsearch_exporter
        - -es.uri=http://10.132.0.23:9200
        - -es.all=true
        ports:
        - containerPort: 9108
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  namespace: monitoring
  labels:
    app: elasticsearch-exporter
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: elasticsearch-exporter
